### ISSUE TITLE
No route matches

### ISSUE THREAD

**Issue by sruttloff** [eugene-sy/redmine_wiki_hierarchical_export#6]
Seems not compatible with Redmine 2.1 got following error:

ActionController::RoutingError (No route matches {:format=>"pdf with hierarchy", :controller=>"export", :action=>"export", :id=>76, :version=>nil}):
  lib/redmine/views/other_formats_builder.rb:29:in `link_to'
  app/views/wiki/show.html.erb:60:in`block in _app_views_wiki_show_html_erb___3374772044565016315_54467320'
  app/helpers/application_helper.rb:456:in `other_formats_links'
  app/views/wiki/show.html.erb:58:in`_app_views_wiki_show_html_erb___3374772044565016315_54467320'
  app/controllers/wiki_controller.rb:92:in `show'

**Comment by eugene-sy** [comment]
check the fix, please

**Comment by sruttloff** [comment]
Perfect - it works.
Thank you very much.
