### ISSUE TITLE
redmine 2.2 suppport ?

### ISSUE THREAD

**Issue by cforce** [eugene-sy/redmine_wiki_hierarchical_export#7]

**Comment by eugene-sy** [comment]
Not yet. I'll fix it in a while.

**Comment by eugene-sy** [comment]
check it, please

**Comment by eugene-sy** [comment]
closing it since the other issue with same theme is fixed

**Comment by cforce** [comment]
Update ur plugin description. It still says only works with redmine 1.3

**Comment by eugene-sy** [comment]
oh, thank you
